use_default_settings: true

server:
  secret_key: "ce9e5b87f9ec6b9ddf5f83c89593cde07684ca9191247fb1615a5fa857deac19"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"

ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "nl"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g

  - name: bing
    engine: bing
    shortcut: b

  - name: duckduckgo
    engine: duckduckgo
    shortcut: d

  - name: wikipedia
    engine: wikipedia
    shortcut: w
    base_url: "https://nl.wikipedia.org/"
